### ISSUE TITLE
[Request] Equality check for Lua values

### ISSUE THREAD

**Issue by rsKliPPy** [mlua-rs/rlua#112]
Is it possible that we get new method on `Context` or `Value` that would call `lua_rawequal` to determine equality between two Lua values? It's currently impossible to determine if e.g. two Lua functions are equal.

My use case is an EventEmitter, just like in Node.js. I don't want to add a new listener (function) if it already exists for the given event name. Existing listeners are saved in the Lua registry using a `Vec<RegistryKey>`.

Awesome library by the way.

**Comment by kyren** [comment]
I'd been meaning to expose `lua_arith` for a while, but you're correct that probably exposing both `lua_rawequal` and `lua_arith` would be extremely useful.

The method that exposed `lua_arith` would almost certainly need to go on `Context` as you would generally need a stack and `lua_arith` can error, but `lua_rawequal` is more interesting.  Technically, I think it would be possible to implement `PartialEq` / `Eq` on `Value`, simply because the only times you would *need* a context to implement it, one is available from either the left or right hand side `Value`, and `lua_rawequal` cannot error.  I'll have to think about it.

**Comment by rsKliPPy** [comment]
If it were implemented as `PartialEq` / `Eq` on `Value`, what would be the right way to call it when we had a `Function` for example? I guess `Value::Function(func1) == Value::Function(func2)`?

And yes, I actually did go through Lua already and just added a TODO to change it to the proper implementation later. :smile:

**Comment by kyren** [comment]
> If it were implemented as PartialEq / Eq on Value, what would be the right way to call it when we had a Function for example? I guess Value::Function(func1) == Value::Function(func2)? Maybe a function on Context accepting two ToLua would be more ergonomic.

I also meant to imply that Table, Function, Thread, and UserData would also implement PartialEq / Eq with themselves in this case.  `Error` is a bit interesting there, since it would never be equal to itself as it is cloned when taken from inside the Lua context, but that is probably fine.

**Comment by khvzak** [comment]
rlua is going to be deprecated soon and this feature is already supported by mlua
