### ISSUE TITLE
Question: how can i bind members

### ISSUE THREAD

**Issue by SetLinux** [mlua-rs/rlua#161]
hey everyone ,
i am struggling to bind a class member ,i can't find a way anywhere to do it for example something like this

`struct Test{pub value : i32}`
now i now i should have UserDat a implemented and what i 've seen add a function to get `value`
but i want to get it like a member not a function ... like this from the lua side
`print(test.value)`
is this possible ?

**Comment by azdle** [comment]
UserData types don't provide any mechanism for the lua VM to access that data stored inside itself.

> The type userdata is provided to allow arbitrary C data to be stored in Lua variables. A userdata value represents a block of raw memory. [...] Userdata has no predefined operations in Lua, except assignment and identity test.
- http://www.lua.org/manual/5.3/manual.html#2.1

You'll want to convert your rust struct into a lua `Table` so that the values can be accessed/modified in Lua.

See this section of the guided tour example for how to do that: https://github.com/kyren/rlua/blob/master/examples/guided_tour.rs#L63-L95

**Comment by kyren** [comment]
What @azdle said is correct of course, the easy thing to do is just create a Lua table out of your structure if you want field access.

However, it is possible to get something that looks like plain field access from a `UserData` by implementing the `__index` metamethod (and possibly the `__newindex` metamethod).  This is a pretty specialized thing to do, however.

**Comment by xRMG412** [comment]
Is there a solid code sample for each of the methods mentioned above? 

>See this section of the guided tour example for how to do that: https://github.com/kyren/rlua/blob/master/examples/guided_tour.rs#L63-L95

This link just shows how you would create a `Table` manually. That is fine but I think most would be looking for a solution that automatically converts a struct into a `Table`. 

>However, it is possible to get something that looks like plain field access from a UserData by implementing the __index metamethod (and possibly the __newindex metamethod)

I have an idea how the `__index` and `__newindex` meta methods would be implemented but I would like to see how people proficient in this library would approach the issue.

Thanks

**Comment by jugglerchris** [comment]
For creating a `Table` I guess some kind of derive macro to derive `ToLua` automatically would be ideal.  I found https://docs.rs/crate/rlua-table-derive/0.1.0 but that's going in the opposite direction.  But otherwise it's creating a table and assigning a bunch of keys.

I think it's a good idea to have examples of `__index`.

**Comment by khvzak** [comment]
rlua is going to be deprecated soon in favour of mlua, which support userdata fields. See [`UserDataFields`](https://docs.rs/mlua/latest/mlua/trait.UserDataFields.html) trait.
