### ISSUE TITLE
Undefined symbol lua_checkstack

### ISSUE THREAD

**Issue by xHyroM** [mlua-rs/rlua#273]
Hello, i'm trying to load `cjson` module with this configuration:

```rust
            Lua::unsafe_new_with_flags(
                StdLib::ALL_NO_DEBUG, // Load all Lua standard libraries apart from debug
                InitFlags::DEFAULT - InitFlags::REMOVE_LOADLIB, // Allow loading binary libraries
            )
```

and code:
```lua
local cjson = require "cjson"

local json = cjson.encode({
    foo = "bar",
    some_object = {},
    some_array = cjson.empty_array
})
```

but i got
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: RuntimeError("error loading module 'cjson' from file '/usr/local/lib/lua/5.4/cjson.so':\n\t/usr/local/lib/lua/5.4/cjson.so: undefined symbol: lua_checkstack\nstack traceback:\n\t[C]: in ?\n\t[C]: in ?\n\t[C]: in function 'require'\n\t[string \"?\"]:1: in main chunk")', cli/src/main.rs:13:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with normal lua, it works great

version: 0.19.5

**Comment by jugglerchris** [comment]
I think the problem (similar to #264) is that we're not exporting the `lua` symbols.  A workaround may be using the `system-lua54` feature (and disabling default features), which would use a Lua library installed on your system instead of compiling one in.

I need to work out the linker options to export the Lua symbols to get it to work with the builtin Lua.

**Comment by jugglerchris** [comment]
Having done some investigation, I think the fix is to the end application.

The ideal fix would be the [export-executable-symbols](https://github.com/rust-lang/rfcs/pull/2841), which is available on nightly but not yet on stable - so if you're using nightly, passing `-Z export-executable-symbols` to cargo should make it work.

Until that's available, you can do it by adding linker flags.  If I add `println!("cargo:rustc-link-arg-examples=-Wl,-export-dynamic");` to `rlua`'s `build.rs`, then for example `target/debug/examples/repl` has Lua (and other) symbols exported.  For an end executable, you'd use [rustc-link-arg-bins](https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-link-arg-binsflag) or similar.  Unfortunately the specific linker option needed may vary for different platforms (this was on Linux).

**Comment by xHyroM** [comment]
Thanks, i'll use nightly version instead 😅

**Comment by devzf** [comment]
I would recommend switching to [mlua](https://crates.io/crates/mlua). it doesn't have those problems. 
rlua unfortunaly is dead.

**Comment by jugglerchris** [comment]
@bigmstone Thanks for reporting your findings!
It may be that rlua needs to include references to functions it doesn't otherwise use (maybe especially in C source files that aren't otherwise referenced) for this case.

**Comment by xHyroM** [comment]
@devzf i dont think rlua is dead, @jugglerchris do a great job here

**Comment by khvzak** [comment]
rlua is going to be deprecated soon in favour of mlua. See  https://github.com/mlua-rs/mlua/blob/master/FAQ.md#loading-a-c-module-fails-with-error-undefined-symbol-lua_xxx-how-to-fix about  about undefined symbols.
